[package]
name = "lazy_static"
# NB: When modifying, also modify html_root_url in lib.rs
version = "1.4.0"
authors = ["Marvin Löbel <loebel.marvin@gmail.com>"]
license = "MIT/Apache-2.0"

description = "A macro for declaring lazily evaluated statics in Rust."
readme = "README.md"
documentation = "https://docs.rs/lazy_static"

repository = "https://github.com/rust-lang-nursery/lazy-static.rs"
keywords = ["macro", "lazy", "static"]
categories = [ "no-std", "rust-patterns", "memory-management" ]
exclude = ["/.travis.yml", "/appveyor.yml"]

[dependencies]
compiler_builtins = {version = "0.1", optional = true}
core = {version = "1.0", optional = true, package = "rustc-std-workspace-core"}
alloc = {version = "1.0", optional = true, package = "rustc-std-workspace-alloc"}

[dependencies.spin]
version = "0.6.0"
optional = true
features = ['rustc-dep-of-std']

[features]
default = ["rustc-dep-of-std"]
spin_no_std = ["spin"]
rustc-dep-of-std = ["compiler_builtins", "core", "alloc"]

[dev-dependencies]
doc-comment = "0.3.1"

[badges]
appveyor = { repository = "rust-lang-nursery/lazy-static.rs" }
travis-ci = { repository = "rust-lang-nursery/lazy-static.rs" }

is-it-maintained-issue-resolution = { repository = "rust-lang-nursery/lazy-static.rs" }
is-it-maintained-open-issues = { repository = "rust-lang-nursery/lazy-static.rs" }

maintenance = { status = "passively-maintained" }
